version: "3.3"
services:
  scheduler:
    image: scheduler
    restart: always
    volumes:
      - "/var/lib/boot2docker:/var/lib/boot2docker"
    environment:
      P2P_FOG_DEV_ENV: production
    ports:
      - 8090:8090
    networks:
      - func_functions
    secrets:
      - basic-auth-user
      - basic-auth-password

  discovery:
    image: discovery
    restart: always
    volumes:
      - "/var/lib/boot2docker:/var/lib/boot2docker"
    environment:
      P2P_FOG_DEV_ENV: production
    ports:
      - 9000:9000
    networks:
      - func_functions
    secrets:
      - basic-auth-user
      - basic-auth-password

  mongo:
    image: mongo:latest
    restart: always
    #volumes:
    #  - /home/docker/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - func_functions

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - func_functions

networks:
  func_functions:
    external: true

secrets:
  basic-auth-user:
    external: true
  basic-auth-password:
    external: true
