version: "3.3"
services:
  scheduler:
    image: registry.gitlab.com/p2p-fog/stack-scheduler:latest
    volumes:
      - "~/.config/p2pfog:/var/lib/boot2docker"
    environment:
      env: production
      P2P_FOG_DEV_ENV: production
    ports:
      - 18080:18080
    networks:
      - func_functions
    secrets:
      - basic-auth-user
      - basic-auth-password
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints:
          - "node.role == manager"
          - "node.platform.os == linux"
          
  discovery:
    image: registry.gitlab.com/p2p-fog/stack-discovery:latest
    volumes:
      - "~/.config/p2pfog:/var/lib/boot2docker"
    environment:
      env: production
      P2P_FOG_DEV_ENV: production
    ports:
      - 19000:19000
    networks:
      - func_functions
    secrets:
      - basic-auth-user
      - basic-auth-password
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints:
          - "node.role == manager"
          - "node.platform.os == linux"

  mongo:
    image: mongo:latest
    restart: always
    #volumes:
    #  - /home/docker/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - func_functions
    deploy:
      placement:
        constraints:
          - "node.role == manager"
          - "node.platform.os == linux"

networks:
  func_functions:
    external: true

secrets:
  basic-auth-user:
    external: true
  basic-auth-password:
    external: true