version: "2.1"

volumes:
  resin-data:

services:
  scheduler:
    build: ./stack-scheduler
    environment:
      P2PFAAS_LOG_ENV: production
      P2PFAAS_DEV_ENV: production
    ports:
      - 18080:18080
    volumes:
      - 'resin-data:/data'
    restart: always

  discovery:
    build: ./stack-discovery
    environment:
      P2PFAAS_LOG_ENV: production
      P2PFAAS_DEV_ENV: production
    ports:
      - 19000:19000
    volumes:
      - 'resin-data:/data'
    restart: always

  learner:
    build: ./stack-learner
    environment:
      P2PFAAS_LOG_ENV: production
      P2PFAAS_DEV_ENV: production
    ports:
      - 19020:19020
    volumes:
      - 'resin-data:/data'
    restart: always

  fn-pigo:
    build: ./fn-pigo
    environment:
      output_mode: "image"
      input_mode: "image"
    restart: always
    # ports:
    #   - 28080:8080

  # fn-loop:
  #   build: ./fn-loop
  #   environment:
  #     mi: 5.0