version: "2.1"

services:
  scheduler:
    build: ./stack-scheduler
    environment:
      P2PFAAS_LOG_ENV: production
      P2PFAAS_DEV_ENV: production
    ports:
      - 18080:18080
    networks:
      - p2pfaas_net

  discovery:
    build: ./stack-discovery
    environment:
      P2PFAAS_LOG_ENV: production
      P2PFAAS_DEV_ENV: production
    ports:
      - 19000:19000
    networks:
      - p2pfaas_net

networks:
  p2pfaas_net:
    driver: "overlay"
